let projects = [
  {
    categorie: "ui-design",
    name: "unknown",
    link_website: null,
    link_github: null,
    preview_img: "./img/ui_design/mockup_unknown.jpg",
    tools: ["xd"],
    description:
      "Conception and design of an app that allows students to get to know famous artists, architects and designers and their creations.",
    images: [
      "img/ui_design/unknown/designer.jpg",
      "img/ui_design/unknown/designer_werk_1.jpg",
      "img/ui_design/unknown/designer_ueberblick.jpg",
      "img/ui_design/unknown/designer_teilen.jpg",
      "img/ui_design/unknown/deisgner_detail_ansicht.jpg",
      "img/ui_design/unknown/gemerkte_erzeugnisse.jpg",
      "img/ui_design/unknown/gemerkte_personen.jpg",
      "img/ui_design/unknown/profil.jpg",
    ],
  },
  {
    categorie: "ui-design",
    name: "Eventrava",
    link_website: null,
    link_github: null,
    preview_img: "./img/ui_design/mockup_eventrava.jpg",
    tools: ["xd"],
    description:
      "Client project: Redesign of an app for the international online community of the dance scene.",
    images: [
      "img/ui_design/eventrava/Carpool_Startseite.png",
      "img/ui_design/eventrava/Community.png",
      "img/ui_design/eventrava/Event.png",
      "img/ui_design/eventrava/Online Classes _Kurs_Ansicht_2.png",
      "img/ui_design/eventrava/Online_Classes.png",
      "img/ui_design/eventrava/Profil _Meine_Fotos.png",
    ],
  },
  {
    categorie: "ui-design",
    name: "WC Wanted",
    link_website: null,
    link_github: null,
    preview_img: "./img/ui_design/mockup_wc_wanted.jpg",
    tools: ["xd"],
    description:
      "Conception and design of WC Wanted, the app that helps everyone to always find the perfect toilet on tour.",
    images: [
      "img/ui_design/wc_wanted/green_front.jpg",
      "img/ui_design/wc_wanted/Wc_Profil_Handy.jpg",
      "img/ui_design/wc_wanted/front.jpg",
      "img/ui_design/wc_wanted/Fav.jpg",
      "img/ui_design/wc_wanted/Bewertung_Handy.jpg",
    ],
  },
  {
    categorie: "web-development",
    name: "Instagram",
    link_website:
      "https://kai-uwe-hella.developerakademie.net/insta/index.html",
    link_github: "https://github.com/KaiUweHella/Insta.git",
    preview_img: "./img/web_development/insta.jpg",
    tools: ["javascript", "html", "css"],
    description:
      "Selected functions as well as the design of Instagram realized independently.",
  },
  {
    categorie: "web-development",
    name: "Lieferando",
    link_website:
      "https://kai-uwe-hella.developerakademie.net/lieferando/index.html",
    link_github: "https://github.com/KaiUweHella/lieferando.git",
    preview_img: "./img/web_development/lieferando.jpg",
    tools: ["javascript", "html", "css"],
    description:
      "Selected functions as well as the design of Lieferando realized independently.",
  },
  {
    categorie: "web-development",
    name: "Notes",
    link_website:
      "https://kai-uwe-hella.developerakademie.net/notiz_app/index.html",
    link_github: "https://github.com/KaiUweHella/notes.git",
    preview_img: "./img/web_development/notes.jpg",
    tools: ["javascript", "html", "css"],
    description:
      "A note app based on Google Notes with overview, archive and trash function.",
  },
  {
    categorie: "web-development",
    name: "QuizApp",
    link_website:
      "https://kai-uwe-hella.developerakademie.net/quiz_app/index.html",
    link_github: "https://github.com/KaiUweHella/QuizApp.git",
    preview_img: "./img/web_development/quizapp.jpg",
    tools: ["javascript", "html", "css"],
    description:
      "Selected functions as well as the design of QuizApp realized independently.",
  },
  {
    categorie: "web-development",
    name: "Pokedex",
    link_website:
      "https://kai-uwe-hella.developerakademie.net/pokedex/index.html",
    link_github: "https://github.com/KaiUweHella/Pokedex.git",
    preview_img: "./img/web_development/pokedex.jpg",
    tools: ["javascript", "html", "css", "xd", "api"],
    description:
      "Based on the pokeapi, this project was implemented with a lot of love for the design and the greatest possible use of the API.",
  },
  {
    categorie: "creative",
    name: "Photoshoot",
    link_website: null,
    link_github: null,
    preview_img: "./img/creative/photoshoot_3.jpg",
    tools: null,
    description: null,
  },
  {
    categorie: "creative",
    name: "Cover Design",
    link_website: null,
    link_github: null,
    preview_img: "./img/creative/cover_2.jpg",
    tools: null,
    description: null,
  },
  {
    categorie: "creative",
    name: "Cover Design",
    link_website: null,
    link_github: null,
    preview_img: "./img/creative/cover_1.jpg",
    tools: null,
    description: null,
  },
  {
    categorie: "creative",
    name: "Photoshoot",
    link_website: null,
    link_github: null,
    preview_img: "./img/creative/photoshoot_1.jpg",
    tools: null,
    description: null,
  },
  {
    categorie: "creative",
    name: "Photoshoot",
    link_website: null,
    link_github: null,
    preview_img: "./img/creative/photoshoot_2.jpg",
    tools: null,
    description: null,
  },
  {
    categorie: "creative",
    name: "Merch Design",
    link_website: null,
    link_github: null,
    preview_img: "./img/creative/merch.jpg",
    tools: null,
    description: null,
  },
];
