let projects = [
  {
    categorie: "ui-design",
    name: "unknown",
    link_website: null,
    link_github: null,
    preview_img: "./img/ui_design/mockup_unknown.jpg",
    tools: ["xd"],
    description:
      "Conception and design of an app that allows students to get to know famous artists, architects and designers and their creations.",
  },
  {
    categorie: "ui-design",
    name: "Eventrava",
    link_website: null,
    link_github: null,
    preview_img: "./img/ui_design/mockup_eventrava.jpg",
    tools: ["xd"],
    description:
      "Client project: Redesign of an app for the international online community of the dance scene.",
  },
  {
    categorie: "ui-design",
    name: "WC Wanted",
    link_website: null,
    link_github: null,
    preview_img: "./img/ui_design/mockup_wc_wanted.jpg",
    tools: ["xd"],
    description:
      "Conception and design of WC Wanted, the app that helps everyone to always find the perfect toilet on tour.",
  },
  {
    categorie: "web-development",
    name: "Instagram",
    link_website: "https://kai-uwe-hella.developerakademie.net/insta/index.html",
    link_github: null,
    preview_img: "./img/web_development/insta.jpg",
    tools: ["javascript", "html", "css"],
    description:
      "Exercise: Implemented selected functions as well as the design of Instagram independently.",
  },
  {
    categorie: "web-development",
    name: "Lieferando",
    link_website: "https://kai-uwe-hella.developerakademie.net/lieferando/index.html",
    link_github: null,
    preview_img: "./img/web_development/lieferando.jpg",
    tools: ["javascript", "html", "css"],
    description:
      "Exercise: Implemented selected functions as well as the design of Lieferando independently.",
  },
  {
    categorie: "web-development",
    name: "Notes",
    link_website: "https://kai-uwe-hella.developerakademie.net/notiz_app/index.html",
    link_github: null,
    preview_img: "./img/web_development/notes.jpg",
    tools: ["javascript", "html", "css"],
    description:
      "Exercise: Created a note app based on Google Notes with overview, archive and trash function.",
  },
  {
    categorie: "web-development",
    name: "QuizApp",
    link_website: "https://kai-uwe-hella.developerakademie.net/quiz_app/index.html",
    link_github: null,
    preview_img: "./img/web_development/quizapp.jpg",
    tools: ["javascript", "html", "css"],
    description:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut.",
  },
  {
    categorie: "web-development",
    name: "Pokedex",
    link_website: "https://kai-uwe-hella.developerakademie.net/pokedex/index.html",
    link_github: null,
    preview_img: "./img/web_development/pokedex.jpg",
    tools: ["javascript", "html", "css", "xd", "api"],
    description:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut.",
  },
  {
    categorie: "creative",
    name: "Photoshoot",
    link_website: null,
    link_github: null,
    preview_img: "./img/creative/photoshoot_3.jpg",
    tools: null,
    description: null,
  },
  {
    categorie: "creative",
    name: "Cover Design",
    link_website: null,
    link_github: null,
    preview_img: "./img/creative/cover_2.jpg",
    tools: null,
    description: null,
  },
  {
    categorie: "creative",
    name: "Cover Design",
    link_website: null,
    link_github: null,
    preview_img: "./img/creative/cover_1.jpg",
    tools: null,
    description: null,
  },
  {
    categorie: "creative",
    name: "Photoshoot",
    link_website: null,
    link_github: null,
    preview_img: "./img/creative/photoshoot_1.jpg",
    tools: null,
    description: null,
  },
  {
    categorie: "creative",
    name: "Photoshoot",
    link_website: null,
    link_github: null,
    preview_img: "./img/creative/photoshoot_2.jpg",
    tools: null,
    description: null,
  },
  {
    categorie: "creative",
    name: "Merch Design",
    link_website: null,
    link_github: null,
    preview_img: "./img/creative/merch.jpg",
    tools: null,
    description: null,
  },
];
